* [Academic Torrents](http://academictorrents.com/)
* [Archive.org](https://archive.org/)
* [Kaggle](https://www.kaggle.com/)
* [Awesome public datasets](https://github.com/caesar0301/awesome-public-datasets)
* [data.world](https://data.world/)